### ISSUE TITLE
No Specifications Panel

### ISSUE THREAD

**Issue by cutterbl** [mthuret/storybook-addon-specifications#104]
Working with latest versions of both Storybook and the Specs addon, I appear to have all of my tests running (had errors in the console when they weren't), but I do not have a 'Specifications' panel being displayed.

I based all of my setup on the documentation, plus the example provided in [react-redux-boilerplate](https://github.com/ShMcK/react-redux-boilerplate), with my tests in files separate from my stories. I'm also using `addDecorator` with the Info addon to give me a little documentation. (I did remove the decorator, to see if that was the issue, but it had no effect.)

**Comment by colt082295** [comment]
I just got the same issue. The fix is to make an addons.js file inside your .storybook directory, and add the `import "storybook-addon-specifications/register";` line in there.
