### ISSUE TITLE
Using Enzyme mount() to render

### ISSUE THREAD

**Issue by ddfridley** [mthuret/storybook-addon-specifications#107]
This is a clarification on the documentation for how to use enzyme within stories.

The current documentation shows that in .storybook/config.js you should add:
```
import {configure} from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```
But in mine, {configure} was already being used elsewhere and I got an error. So this is what worked for me:
```
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
```

Now, on to using enzyme.  The current documentation shows: 
```
stories.add('Hello World', function () {
  const story =
    <button onClick={action('Hello World')}>
      Hello World
    </button>;

  specs(() => describe('Hello World', function () {
    it('Should have the Hello World label', function () {
      let output = mount(story);
      expect(output.text()).toContain('Hello World');
    });
  }));

  return story;
});
```

But what happens with this is that the story is rendered into output, and then the story is returned and rendered in the browser.  This is two separate renders, and the expect() tests are done on the version that you are not seeing on the screen.

Here is a way to do the same thing, while only rendering once, and the expect() tests are done against what you see in the browser.
```
var output; // before each story, we need to clear the previously rendered output

stories.add('Hello World', function () {
  if(output) 
   output.unmount();
  const story =
    <button onClick={action('Hello World')}>
      Hello World
    </button>;

  setTimeout( ()=>{ // execute this after Storybook has rendered the simple div returned by this story
  output=mount(story,{attachTo: document.getElementById('story')}) // mount the story in enzyme and in the browser
   specs(() => describe('Hello World', function () {
     it('Should have the Hello World label', function () {
       expect(output.text()).toContain('Hello World');
     });
   }));
 })

  return <div id='story'></div>;
});
```
I have not run this with Jest, so I don't know if the asynchronous execution will cause issues.  If anyone does, please update this.

If you wanted to click on the button as part of your test, you could use:

`output.find('a').simulate('click',{preventDefaults: ()=>{},stopPropagation: ()=>{}, nativeEvent: {stopImmediatePropagation: ()=>{}}})`

This simulates the click, and you can see the result in the browser.  You have to pass a dummy event that defines all the properties you consume in your event handler,

I have found it useful to look at styles within the browser, to do a sanity check that renders are functioning as expected.  I'm doing a lot of state changes, transitions and animations.  I know that some say that you should just need to look at the react properties- but if you want to look at css in the browser try this:

```
import {ReactWrapper, mount} from "enzyme";
ReactWrapper.prototype.getComputedStyle=function(attr){
	return window.getComputedStyle(this.getDOMNode(),null)[attr];
}
...
const height=parseFloat(output.getComputedStyle('height'))
```

**Comment by jonwilliams-bluescape** [comment]
I spent a lot of time last night following these instructions and it didn't quite work.
Got up this morning and it did 🤷‍♂ So, thanks!
see also:
https://github.com/mthuret/storybook-addon-specifications/issues/110

**Comment by gpsarkar** [comment]
Same thing using decorators and enzyme. 

`import { shallow, mount, render } from 'enzyme';
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });`

`export const MyStory = () => <MyComponent />;
MyStory.story = {
  decorators: [storyFn => {      
    setTimeout(()=>{
          let wrapper = mount(storyFn(), {attachTo: document.getElementById('story')});
          setTimeout(()=>{wrapper.find('button').simulate('click')}, 2000);
    }, 0);
    return (<div id='story'>
        {storyFn()}
      </div>)
  }],
};
`

You can add specs as well if you need to assert something.

`import { specs, describe, it, } from 'storybook-addon-specifications'`

`  decorators: [storyFn => {      
    setTimeout(()=>{
      specs(() => describe('Interaction tests', function () {
        it('should should show hello world' function () {
          let wrapper = mount(storyFn(), {attachTo: document.getElementById('seismic-story')});
          expect(wrapper.text()).toContain('Hello World');
          // Simulate actions or do other assertions...
        })
      }))
    }, 0);
    return (<div id='seismic-story'>
        {storyFn()}
      </div>)
  }],
`
