### ISSUE TITLE
Shows up in other panels

### ISSUE THREAD

**Issue by Ronald-Baars** [mthuret/storybook-addon-specifications#111]
The test results show up in other panels, such as the one from `storybook-addon-jsx` and `storybook-readme`

<img width="415" alt="Schermafbeelding 2019-03-27 om 15 11 21" src="https://user-images.githubusercontent.com/6582045/55082806-a2564e80-50a2-11e9-9b7c-d478c447332a.png">

**Comment by CPedrini** [comment]
@Ronald-Baars did you figured out how to fix this?

**Comment by susannakosic** [comment]
Hi, I am using v 2.1.2 and step into this issue. How can I get the fix on my env?

**Comment by CPedrini** [comment]
@susannakosic just download the new version, 2.1.3. It was already merged.

**Comment by susannakosic** [comment]
thank you! @CPedrini

**Comment by jonwilliams-bluescape** [comment]
Should be (mostly) fixed now
