### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by dkulakowska** [mthuret/storybook-addon-specifications#112]
Hi, 

My team is switching to storybook-addon-specifications, but after the initial setup, all of us keep getting following warning:

<img width="1436" alt="Screenshot 2019-03-28 at 15 16 47" src="https://user-images.githubusercontent.com/31188583/55166965-67225100-5170-11e9-89ee-b1a44cd0f5a3.png">

We get that even on a completely new react project.

Any idea how to fix it?

**Comment by yoyoys** [comment]
I have same problem, I've use `@storybook/vue`.

**Comment by barabba9174** [comment]
Same issue for me

**Comment by mwilkins91** [comment]
I'm having this issue as well

**Comment by coltontravers** [comment]
Same here.

**Comment by jonwilliams-bluescape** [comment]
Don't have time for a PR, but:
in 
src/manager.js
change
`render: () => <Specifications api={api} channel={channel} />`
to
`render: ({ active, key }) => <Specifications api={api} channel={channel} key={key} active={active} />`

This is likely already in a PR somewhere for making the tab context-aware

**Comment by jonwilliams-bluescape** [comment]
https://github.com/CPedrini/storybook-addon-specifications/commit/6c1a6c0caef836c15c0669c4e918054d04264fd0

**Comment by mthuret** [comment]
Hi! Like I said in earlier issue, I don't have the personal time to maintain this project anymore. I'm happy to give the ownership to anyone that would be interested to take over.

**Comment by jonwilliams-bluescape** [comment]
I'm happy to take it for now (although I'll likely end up in the same boat)

**Comment by jonwilliams-bluescape** [comment]
should work with 2.1.5
