### ISSUE TITLE
Styling issue with dark theme

### ISSUE THREAD

**Issue by soundstep** [mthuret/storybook-addon-specifications#116]
The color of the text in the "Specifications" panel does not follow storybook themes.

In the storybook config, with:
```
addParameters({
    options: {
        theme: themes.dark,
        showPanel: true
    }
});
```

I get:

![storybook-specs-dark](https://user-images.githubusercontent.com/133293/57370193-6fb27200-7187-11e9-8a86-53693485af9a.png)

**Comment by jonwilliams-bluescape** [comment]
+1 
(alternatively, remove the !important on the css style)

**Comment by jonwilliams-bluescape** [comment]
waiting on npm access and will fix

**Comment by jonwilliams-bluescape** [comment]
should work with 2.1.5
