### ISSUE TITLE
setProps doesn't work when react-storybook-addon-backgrounds is on

### ISSUE THREAD

**Issue by vidaaudrey** [mthuret/storybook-addon-specifications#13]
When the backgrounds addon is on, the setProps doesn't work. This could be the problem of the backgrounds addon. I'm just wondering if anyone know what might cause this and if it can be fixed at specifications addon side.
1. Working code
   ![image](https://cloud.githubusercontent.com/assets/10999093/18613084/6e6e7c8e-7d26-11e6-8b92-bc3f95e5a21c.png)
2. Fails if I use setProps instead of mount(...);
   ![image](https://cloud.githubusercontent.com/assets/10999093/18613092/b0cad348-7d26-11e6-9c16-7d7dd1dcfb88.png)

**Comment by mthuret** [comment]
It is the same issue that existed with the knobs addons and was described here https://github.com/storybooks/storybook-addon-knobs/issues/60 
In order for those two addons to work correctly, the render function of the background decorator should be pure.

**Comment by mthuret** [comment]
Will be reopened if it need actions on the specs addon side.
