### ISSUE TITLE
"Action Logger" tab disappeared

### ISSUE THREAD

**Issue by rohit-ravikoti** [mthuret/storybook-addon-specifications#14]
Hi,
Thank you so much of this addon. It is proving to be very helpful!

For some reason, I am unable to see the "Action Logger" tab in the bottom panel. Instead, it just gets replaced with the "Specifications" tab. I am using `"@kadira/storybook": "^2.5.2"`.

Am I missing a configuration?

**Comment by mnmtanish** [comment]
Hi, please add `import '@kadira/storybook/addons'; ` to your `addons.js` file. It will add the default set of addons including the action logger.

**Comment by rohit-ravikoti** [comment]
It worked! thanks!
