### ISSUE TITLE
Mocha Async Test (done)

### ISSUE THREAD

**Issue by Hosar** [mthuret/storybook-addon-specifications#25]
Hi, how can I test async actions? It's possible?

I wanted to have my enzyme tests and my redux test on one single place.

```
return store.dispatch(actions.asyncAction(value)).then((res) => {
  expect(res).to.be.true;
});
```

But it always returns **true** even if res is false. Then tried with **done**, and throw this error: _TypeError: done is not a function_

```
it('some test', (done) => {
    return store.dispatch(actions.asyncAction(value)).then((res) => {
        expect(res).to.be.true;
        done();
   });
});

```
It's possible?

Thanks in advance.

**Comment by mthuret** [comment]
Hi @Hosar,

I believe it's currently not possible. When executing the test with storybook, you are using the `it` implementation that I've done for this addon. That's why you don't have the `done` function. 

We are currently investigating on a way to execute the tests server side so that you can use fully jest. https://github.com/mthuret/storybook-addon-specifications/issues/17 (bottom)

Also, I'm curious about the motivation behind 'enzyme tests and my redux test'. Is that because you find is more convenient, or you also want to display redux test on storybook?

**Comment by Hosar** [comment]
Hi @mthuret  first thank for this cool plugin, I really like to work with storybook.

What I tried to do was to test the behavior of my components. _And it's actually working._
e.g.
```
specs(() => describe('Vendor Products', () => {
         it('should add to favorites', () => {
                const product = fakeProduct;

                const addToFavorites = () => {
                    store.dispatch({
                        type: constants.actions.ADD_TO_FAVORITES,
                        payload: product
                    });
                };

                const wrapper = mount(
                    <Favorites addToFavorites={addToFavorites} />
                );

                store.subscribe(() => {
                    const { productsByVendor } = store.getState();
                    expect(productsByVendor.lastAddedToFavorites).to.equal(product.id);
                });

                wrapper.find('button').simulate('click');
            });
}));

```
So now I can test UI features (enzyme) and expected behavior (redux). And there is no need for **done** as I was expecting.

**Comment by mthuret** [comment]
Hey @Hosar, that's nice you find a way to test your redux action along with your component :D 

Do you think it misses an entry in the documentation for explaining those kind of things?

**Comment by therealparmesh** [comment]
I am attempting to address this issue in https://github.com/mthuret/storybook-addon-specifications/pull/47

**Comment by ShibumiParmesh** [comment]
Can we close this issue as per https://github.com/mthuret/storybook-addon-specifications/issues/48?

**Comment by therealparmesh** [comment]
Can we close this issue as per #48?
