### ISSUE TITLE
Specifications tab not showing

### ISSUE THREAD

**Issue by dclawson** [mthuret/storybook-addon-specifications#33]
Followed the documentation to install the specification addon, however the tab does not show in the UI.

Starting with a `create-react-app` base with the following packages:

```json
  "devDependencies": {
    "@kadira/storybook": "^2.35.3",
    "@kadira/react-storybook-addon-info": "^3.3.0",
    "babel-plugin-add-module-exports": "^0.2.1",
    "storybook-addon-specifications": "^1.0.15",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "enzyme": "^2.7.1",
    "eslint": "^3.0.1",
    "eslint-config-standard": "^5.1.0",
    "eslint-config-standard-react": "^3.0.0",
    "eslint-plugin-babel": "^3.2.0",
    "eslint-plugin-jasmine": "^2.2.0",
    "eslint-plugin-promise": "^2.0.0",
    "eslint-plugin-react": "^6.0.0",
    "eslint-plugin-standard": "^2.0.0",
    "expect": "^1.20.2",
    "jest-enzyme": "^2.1.2",
    "react-addons-test-utils": "^15.4.2",
    "react-scripts": "0.9.0"
  },
  "dependencies": {
    "radium": "^0.18.1",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
```

.addons.js file:

```js
import '@kadira/storybook/addons'
import 'storybook-addon-specifications/register'
```

buttons.js

```js
import React from 'react'
import { storiesOf, action } from '@kadira/storybook'
import { specs, describe, it } from 'storybook-addon-specifications'

import { mount } from 'enzyme'
import expect from 'expect'

import Button from '../src/components/Button'

storiesOf('Button', module)
  .add('Hello World', () => {
    const story =
      <Button onClick={action('Hello World')}>
        Hello World
      </Button>

    specs(() => describe('Hello World', function () {
      it('Should have the Hello World label', function () {
        let output = mount(story)
        expect(output.text()).toContain('Hello World')
      })
    }))

    return story
})
```

UI:

![image](https://cloud.githubusercontent.com/assets/1086571/23789300/261981e8-0572-11e7-9942-72f32c867abb.png)

Any ideas?

**Comment by mthuret** [comment]
Hi @dclawson,

I just tried and it works normally. My step: 

1. create-react-app
2. copy & paste your dependencies
3. getstorybook -f 
4. add a webpack.config.js file for enzyme (see the example inside the repo)
4. copy and paste your story

Can you try to do that?
If that still fails, maybe there's an error message that could help me figuring out what's going on.

**Comment by dclawson** [comment]
Hi @mthuret, thank you for testing this for me.

Are you using a .addons.js file at all for your `import 'storybook-addon-specifications/register'`?

Is your `webpack.config.js` inside your `.storybook` folder?

I have tried with a fresh create react app and still have no specifications tab and no console errors.

**Comment by dclawson** [comment]
Thanks @mthuret . 

For some reason i had `.addons.js` rather than `addons.js`.
