### ISSUE TITLE
Asynchronous Mocha tests

### ISSUE THREAD

**Issue by therealparmesh** [mthuret/storybook-addon-specifications#48]
I just wanted to bump the need for supporting asynchronous Mocha tests. I believe that this is a highly valuable feature for this addon as it allows for things like testing behavior around server calls and advanced Redux operations.

I went ahead and made a pull request (https://github.com/mthuret/storybook-addon-specifications/pull/47) against this issue. I hope it helps.

Thank you for this awesome addon and keep up the great work!

**Comment by mthuret** [comment]
PR merged :)
