### ISSUE TITLE
Error with more complex components

### ISSUE THREAD

**Issue by tomitrescak** [mthuret/storybook-addon-specifications#7]
Hi, when testing more complex comnponents and more then 1 specification is present I receive this errors when doing page reload:

![screen shot 2016-09-06 at 4 18 22 pm](https://cloud.githubusercontent.com/assets/2682705/18263521/edf944e8-744d-11e6-8281-889830abde8e.png)

Removing all but one specification in all cases leads to no errors in the console.

**Comment by mthuret** [comment]
Hi ! Is it possible for you to post the complex component or explain what's complex with it ?

**Comment by mthuret** [comment]
I'll close it, please reopen it if you have more detail about it.
