### ISSUE TITLE
Jest is undefined in Specifications tab

### ISSUE THREAD

**Issue by tsnolan23** [mthuret/storybook-addon-specifications#78]
We're loading the tests from external files because we use the Jest CLI, in addition to storybook.  We have several tests that utilize the `jest.fn()` mock function.  

In the terminal, the test passes, but in the Storybook Specifications tab, it fails and states that `jest is not defined` 

Is this by design? Is there any way to include the jest global?

**Comment by mthuret** [comment]
Hi @tsnolan23 can you post some code of your stories file?

**Comment by tsnolan23** [comment]
@mthuret 

In `.storybook/addons.js`, I register the addon:
```
import 'storybook-addon-specifications/register'
```

In `.storybook/config.js`, I override default Jest `descibe`, `it`, etc.:
```
import { beforeEach, describe, it } from 'storybook-addon-specifications'
import expect from 'expect'
window.beforeEach = beforeEach
window.describe = describe
window.expect = expect
window.it = it
```

My component test code:
```
it('Handles click event', () => {
  const mockFunction = jest.fn()
    button.setProps({
      onClick: mockFunction
    })
    button.simulate('click')
    expect(mockFunction).toHaveBeenCalledTimes(1)
})
```

Then in the story I add the `spec`
```
elementStories.add('Button', withReadme(ButtonReadme, () => {
  specs(() => ButtonTests)
  ...other code...
}))
```

Then here is the result in the specifications tab:
![storybook_jest_not_defined](https://user-images.githubusercontent.com/12575994/32072194-64e51816-ba57-11e7-9c31-a7912c460324.PNG)

**Comment by mthuret** [comment]
For the addon to work you need to have code that is executable from the front-end. I believe this can't. 

```
const mockFunction = jest.fn()
```

You can still use another mock library to achieve the same thing if you want to have it as a spec.

**Comment by tsnolan23** [comment]
@mthuret Ah, fair enough. We just had all of our tests written with the built in Jest mock, so not looking to re-write.  I did find a slightly hackish way to fix it by also including jest mock in the storybook config:

```
import jest from 'jest-mock'
window.jest = jest
```
This is not the same global Jest object provided in the CLI, but it does resolve the problem as it includes the function I need. 

This can be closed.
