### ISSUE TITLE
Supporting Shallow Rendering

### ISSUE THREAD

**Issue by vidaaudrey** [mthuret/storybook-addon-specifications#8]
When using shallow instead of mount, the following exception will appear:
![image](https://cloud.githubusercontent.com/assets/10999093/18337139/c97624e2-7542-11e6-912c-4b8b0ced1f24.png)
@mthuret I wonder if shallow rendering is going to be supported in the future features. BTW, huge thanks for creating this amazing addon!!!

**Comment by mthuret** [comment]
I'm not sure that's because of shallow rendering. I tried to use shallow instead of mount with the Hello World example and everything went fine. However, your error looks like the #7 one. Does your component/test has something special ?

**Comment by mthuret** [comment]
Seems to be similar than #7. I'll close this one and will wait for more information.

**Comment by ndelangen** [comment]
Shallow rendering testing seems to work just fine for me in combination with this plugin, but maybe the complexity of the component matters? https://github.com/mthuret/storybook-addon-specifications/issues/7
