### ISSUE TITLE
Storybook 3 support

### ISSUE THREAD

**Issue by husayt** [mthuret/storybook-addon-specifications#96]
This is a very useful addon. Although it seems like project hasn't been updated for long time. There are number of pull requests waiting, storybook has moved on a long way and is at version 3.3. It would be great to keep this project alive or maybe to add it to storybook project supported addons. 

Thanks

**Comment by mthuret** [comment]
Hi @husayt, it's true that lately I don't have time to focus on this project anymore. But if you or anyone on  the community wants to keep maintaining it, I'm very open to open the team. Just tell me :)

**Comment by jonwilliams-bluescape** [comment]
Working now with 5.2 beta 40!
